[book]

title = "Vulkan Tutorial (Rust)"
authors = ["Kyle Mayes"]

description = "A Vulkan tutorial for Rust."

language = "en"
multilingual = false

src = "src"

edition = "edition2018"

[output.html]

git-repository-url = "https://github.com/KyleMayes/vulkanalia"

[preprocessor.vk]

command = "vk-preprocessor"
renderer = ["html"]
